### ISSUE TITLE
API Developers - User Login (Target 2)

### ISSUE THREAD

**Issue by JonathanMCurtis** [JonathanMCurtis/SmallProject#6]
Once the User database fields are fit to specification, it should be possible to create the API endpoints for user-related functions.
- [x] Design a 'CreateUser' API endpoint, which creates a user account record.
- [x] Design a 'Login' API endpoint, which confirms an accurate password was provided for a given username.

**Comment by tuckerf42** [comment]
[For_small_project.zip](https://github.com/JonathanMCurtis/SmallProject/files/4670182/For_small_project.zip)
This file holds the Login and Create New User Code, The only edits I have to do to it is:
I have to change the local host to the actually host address, and I need the name of the database.

**Comment by tuckerf42** [comment]
These matters have been fixed and the code is upload; however further testing needs to be done, and communication with the front end needs to be done.

**Comment by JonathanMCurtis** [comment]
Pending changes required from the Front-End team ( @idelmr @MasonBenell ), the Login.php and CreateUser.php endpoints are fully functional at this time (have passed both review and testing.)

These files will be added to the Target2 working branch (along with documentation on their use.)
