### ISSUE TITLE
Front End Developers - Login Page (Target 2)

### ISSUE THREAD

**Issue by JonathanMCurtis** [JonathanMCurtis/SmallProject#9]
The design specifications for each front-end section are pretty loose, this lists the minimum requirements:
- [ ] User Login
  - [x] Text fields for username and password
  - [x] Button to attempt login
  - [ ] Call to API's login function
  - [ ] Error message (not alert box) for invalid login
- [ ] User Creation
   - [x] Text fields for username and password
   - [x] Button to attempt user creation
   - [ ] Call to API's createUser function
   - [ ] Confirm the username is currently not in use
   - [ ] Optional: Automatically login after account creation (rather than forcing the user to login)?
---
- [ ] Add [form validation](https://jaredpalmer.com/formik/docs/overview) for error and pattern-checking
- [ ] Install and use [cookies](https://github.com/reactivestack/cookies/tree/master/packages/universal-cookie) for maintaining user data and logging in automatically

**Comment by idelmr** [comment]
I believe it's a security issue if we automatically log-in users after signing up, but:
* I don't think security is a priority in this project,
* we don't do email verficiation, so it's pointless to require the user to sign up and *then* login, and
* it's easy to add it to the code

**Comment by JonathanMCurtis** [comment]
Definitely agree. If security were a target here, we would definitely be looking at more pressing issues (like open username/password API access.)

Appreciate the additions of form validation and session info.
